# Generated by Django 4.2 on 2023-04-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_exam_pdf_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='url',
            new_name='pdf_url',
        ),
    ]
