# Generated by Django 4.2 on 2023-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_url_exam_pdf_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examination',
            new_name='Source',
        ),
    ]
