# Generated by Django 4.2 on 2023-04-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_examination_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
    ]
